name: elysia-basics

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - '4317:4317'
      - '4318:4318'
      - '5778:5778'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '9411:9411'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '16686:16686'
